### ISSUE TITLE
🐛cb login servers error page when theres no input fields

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#207]
On current master 👇 

![p2c-bug-1](https://user-images.githubusercontent.com/14337958/36555548-007cf7c4-180b-11e8-958b-0d7bc728004e.gif)

Bug seems to be a frontend/react issue as server does the thing it's _currently_ meant to...

**Comment by RogeredBacon** [comment]
Currently it errors whenever there's no input or when the email input is not a valid email address. It returns the expected error message (successfully) when the email or password is not in the database. So it seems like the bug is before the queries. I was looking at this yesterday and will try to get it fixed
