### ISSUE TITLE
DB schema review

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/DataPower#210]
In the process of doing #209, I noticed a few things about the schema that should probably be changed.

* [ ] Many column names are in camel case. The widespread convention is for SQL column names to be in `snake_case`.
* [ ] The use of `date` as a column name, aside from being problematic for using a SQL keyword, is ambiguous. What date is being recorded here? The date when the row is created? Updated? A better name is necessary so it's purpose can be gleaned from reading the schema. It's common to have one field for the time a record was created and another for the time a record was last updated.
* [ ] Names should not be abbreviated (e.g. `hash_pwd` can simply be `password`, `cb_id` -> `community_business_id`, `cbusiness` -> `community_businesses`)
* [ ] `token` is ambiguous: what kind of token and what is it for? I think this is used for password resets, right?
* [ ] `tokenExpire` is a `BIGINT`, presumably it's meant to be a UNIX timestamp? In which case wouldn't `TIMESTAMP` be a more meaningful datatype?
* [ ] Is there are reason we are collecting the sex of users? Are we actually talking about sex, or are we talking about gender? Do we really need either?

No action yet, would prefer tests on the query functions first.

**Comment by RogeredBacon** [comment]
The token expire is currently milliseconds until the token expires, which I think is 30mins, though maybe a better type of int could be used.

We're talking about sex rather than gender and this was a definite datapoint that Sonja wanted.

The real point of the app is to help CB's compete with larger companies in terms of tailoring their services towards certain customer types. The CB's need to know if they're only attracting young/old woman/men, so that they can then focus on their core users or try to diversify; and then whether what they're doing is working.

We've never really looked properly at the schema and I agree it definitely needs to be done, renaming the columns will make it a fair bit of work because of how much relies on them but the tests will hopefully sort most of it.

**Comment by eliascodes** [comment]
These are all addressed by proposals in #357, so closing this.
