### ISSUE TITLE
Inconsistent way of handling incorrect dB queries

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#244]
Some db queries return an empty array if they can’t find what they’re looking for, whereas other return a rejected promise. Moving forward to would be good to pick one consistent way of doing this 😊

**Comment by RogeredBacon** [comment]
Yeah we need to overhaul all of the routes and queries to use a uniform way of returning results/errors. Currently there's like 4/5 different types of response going on.

**Comment by eliascodes** [comment]
IMO:

Since promises represent future values, they should reject only if it is impossible to return a value. In JS, we live a world where we have a "value" (`null`) that represents "no-value". Think about how `pg` uses promises: if no records are found, the promise doesn't reject, it resolves with an "empty" value (in most cases an empty array in `result.rows`).

There are two cases when thinking about return values:
1. Queries that return 0-1 record(s)
   * These promises represent a single record, so should resolve with `null` if no records found.
2. Queries that return 0-Infinity records
   * These promises represent collections of records, so should always resolve with an array. If no matching records are found, they should simply resolve with an empty array.

With this convention, we can be sure that any rejected promises represent serious errors outside of the normal flow of application logic. Otherwise we'd need logic inside `catch` to determine if a promise was rejected because something went wrong, or just because no record was found.

**Comment by astroash** [comment]
I like the idea of not unnecessarily rejecting promises, but you've lost me a little on points 1 & 2. 

In your description, what's the difference between **point 1** returning `null` if _"no records found"_ and **point 2** returning `[]` if _"no matching records found"_.

**Comment by eliascodes** [comment]
> In your description, what's the difference between point 1 returning null if "no records found" and point 2 returning [] if "no matching records found".

Think about the difference between:
1. "Find the user with an id of 2"
2. "Find all users with the name 'John'"

**Comment by astroash** [comment]
Lol, that's a very complex description for wether or not our result needs to return an array.

**Comment by astroash** [comment]
@eliascodes following on from above. Do you think we should return an `Error` or `null` for a query that is trying to `INSERT` data into the db?

**Comment by eliascodes** [comment]
@astroash that would cause an error in SQL so IMO the promise should be rejected. It's indicative of a programmer error, which we should not try to recover from.

**Comment by astroash** [comment]
@eliascodes do you think this needs to be outlined somewhere in the docs? I _think_ we only mention expected data for apis atm.

**Comment by eliascodes** [comment]
@astroash If you want it in the docs, go for it. IMO this is more best practices than project convention, but I'm not against it going in.

**Comment by astroash** [comment]
😉
